settings:
  title: 'Hostza Status'
  url: 'https://status.hostza.app' # used for Slack messages
  logo: icon_hostza.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: website # unique identifier
    name: website
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://hostza.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Documentation
    name: Documentation
    description: 'Built for anything connected to the Internet.'
    url: 'https://docs.hostza.app'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
